name: PR title format

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  check:
    name: conventional-pr-title:required
    runs-on: ubuntu-latest
    steps:
      # Conventional Commits v1.0:
      #   verb: description
      #   verb!: description of breaking change
      #   verb(scope): description
      #   verb(scope)!: description
      - run: |
          if [[ "$TITLE" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test|revert)(\([-a-zA-Z0-9,]+\))?\!?\: ]]; then
            echo pass
          else
            echo "PR title does not match Conventional Commits"
            exit 1
          fi
